TELEGRAM_EVENT_SUBJECT = "telegram.message.event"
AGENT_RESPONSE_SUBJECT = "agent.response.event"
TELEGRAM_EVENT_SIGNAL_NAME = TELEGRAM_EVENT_SUBJECT
TELEGRAM_MESSAGE_EVENT_NAME = TELEGRAM_EVENT_SUBJECT
