import json
import os

# Engine configuration
categories = ['general']
paging = False
weight = 1
api_key = '' # SearXNG will populate this from settings.yml

# API Endpoint (using gemini-2.5-flash as it's the latest stable version supporting grounding)
url = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}'

def request(query, params):
    # Prepare the JSON payload for Gemini with Google Search tool enabled
    payload = {
        "contents": [{
            "parts": [{"text": query}]
        }],
        "tools": [
            {"googleSearch": {}}
        ]
    }
    params['method'] = 'POST'
    params['data'] = json.dumps(payload)
    params['headers']['Content-Type'] = 'application/json'
    
    # Retrieve API key: use the injected variable or environment variable
    current_api_key = api_key
    if not current_api_key or current_api_key == '${GEMINI_API_KEY}':
        current_api_key = os.environ.get('GEMINI_API_KEY', '')
    
    params['url'] = url.format(api_key=current_api_key)
    
    return params

def response(resp):
    results = []
    
    try:
        data = json.loads(resp.text)
        candidate = data.get('candidates', [{}])[0]
        
        # 1. Extract the text generated by Gemini
        parts = candidate.get('content', {}).get('parts', [])
        if parts:
            answer = parts[0].get('text', '')
            if answer:
                results.append({
                    'answer': answer,
                })
        
        # 2. Extract grounded search links from groundingMetadata
        metadata = candidate.get('groundingMetadata', {})
        chunks = metadata.get('groundingChunks', [])
        
        for chunk in chunks:
            web = chunk.get('web', {})
            uri = web.get('uri')
            title = web.get('title')
            
            if uri and title:
                results.append({
                    'url': uri,
                    'title': title,
                    'content': 'Source provided by Gemini Search'
                })
                
    except (KeyError, IndexError, json.JSONDecodeError):
        pass
        
    return results